apiVersion: v1
kind: PersistentVolume
metadata:
  name: sandbox-app-database-storage
  labels:
    app.kubernetes.io/name: sandbox-app-database
    app.kubernetes.io/part-of: sandbox-app
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /var/lib/sandbox-app/database
    type: DirectoryOrCreate
