// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppAccountsColumns holds the columns for the "app_accounts" table.
	AppAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "email", Type: field.TypeString, Default: ""},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "picture", Type: field.TypeString, Default: ""},
	}
	// AppAccountsTable holds the schema information for the "app_accounts" table.
	AppAccountsTable = &schema.Table{
		Name:       "app_accounts",
		Columns:    AppAccountsColumns,
		PrimaryKey: []*schema.Column{AppAccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "appaccount_email",
				Unique:  false,
				Columns: []*schema.Column{AppAccountsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppAccountsTable,
	}
)

func init() {
	AppAccountsTable.Annotation = &entsql.Annotation{
		Table: "app_accounts",
	}
}
