// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sandbox-nextjs/src/ent/appaccount"
)

// AppAccountCreate is the builder for creating a AppAccount entity.
type AppAccountCreate struct {
	config
	mutation *AppAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AppAccountCreate) SetCreatedAt(v time.Time) *AppAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AppAccountCreate) SetNillableCreatedAt(v *time.Time) *AppAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AppAccountCreate) SetUpdatedAt(v time.Time) *AppAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AppAccountCreate) SetNillableUpdatedAt(v *time.Time) *AppAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOidcSubject sets the "oidc_subject" field.
func (_c *AppAccountCreate) SetOidcSubject(v string) *AppAccountCreate {
	_c.mutation.SetOidcSubject(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *AppAccountCreate) SetEmail(v string) *AppAccountCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *AppAccountCreate) SetNillableEmail(v *string) *AppAccountCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AppAccountCreate) SetName(v string) *AppAccountCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *AppAccountCreate) SetNillableName(v *string) *AppAccountCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetPicture sets the "picture" field.
func (_c *AppAccountCreate) SetPicture(v string) *AppAccountCreate {
	_c.mutation.SetPicture(v)
	return _c
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (_c *AppAccountCreate) SetNillablePicture(v *string) *AppAccountCreate {
	if v != nil {
		_c.SetPicture(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AppAccountCreate) SetID(v int) *AppAccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AppAccountMutation object of the builder.
func (_c *AppAccountCreate) Mutation() *AppAccountMutation {
	return _c.mutation
}

// Save creates the AppAccount in the database.
func (_c *AppAccountCreate) Save(ctx context.Context) (*AppAccount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppAccountCreate) SaveX(ctx context.Context) *AppAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppAccountCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := appaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := appaccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Email(); !ok {
		v := appaccount.DefaultEmail
		_c.mutation.SetEmail(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := appaccount.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Picture(); !ok {
		v := appaccount.DefaultPicture
		_c.mutation.SetPicture(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppAccountCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AppAccount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AppAccount.updated_at"`)}
	}
	if _, ok := _c.mutation.OidcSubject(); !ok {
		return &ValidationError{Name: "oidc_subject", err: errors.New(`ent: missing required field "AppAccount.oidc_subject"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "AppAccount.email"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AppAccount.name"`)}
	}
	if _, ok := _c.mutation.Picture(); !ok {
		return &ValidationError{Name: "picture", err: errors.New(`ent: missing required field "AppAccount.picture"`)}
	}
	return nil
}

func (_c *AppAccountCreate) sqlSave(ctx context.Context) (*AppAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppAccountCreate) createSpec() (*AppAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &AppAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(appaccount.Table, sqlgraph.NewFieldSpec(appaccount.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(appaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(appaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.OidcSubject(); ok {
		_spec.SetField(appaccount.FieldOidcSubject, field.TypeString, value)
		_node.OidcSubject = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(appaccount.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(appaccount.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Picture(); ok {
		_spec.SetField(appaccount.FieldPicture, field.TypeString, value)
		_node.Picture = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppAccount.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AppAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AppAccountCreate) OnConflict(opts ...sql.ConflictOption) *AppAccountUpsertOne {
	_c.conflict = opts
	return &AppAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AppAccountCreate) OnConflictColumns(columns ...string) *AppAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AppAccountUpsertOne{
		create: _c,
	}
}

type (
	// AppAccountUpsertOne is the builder for "upsert"-ing
	//  one AppAccount node.
	AppAccountUpsertOne struct {
		create *AppAccountCreate
	}

	// AppAccountUpsert is the "OnConflict" setter.
	AppAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AppAccountUpsert) SetUpdatedAt(v time.Time) *AppAccountUpsert {
	u.Set(appaccount.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppAccountUpsert) UpdateUpdatedAt() *AppAccountUpsert {
	u.SetExcluded(appaccount.FieldUpdatedAt)
	return u
}

// SetOidcSubject sets the "oidc_subject" field.
func (u *AppAccountUpsert) SetOidcSubject(v string) *AppAccountUpsert {
	u.Set(appaccount.FieldOidcSubject, v)
	return u
}

// UpdateOidcSubject sets the "oidc_subject" field to the value that was provided on create.
func (u *AppAccountUpsert) UpdateOidcSubject() *AppAccountUpsert {
	u.SetExcluded(appaccount.FieldOidcSubject)
	return u
}

// SetEmail sets the "email" field.
func (u *AppAccountUpsert) SetEmail(v string) *AppAccountUpsert {
	u.Set(appaccount.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AppAccountUpsert) UpdateEmail() *AppAccountUpsert {
	u.SetExcluded(appaccount.FieldEmail)
	return u
}

// SetName sets the "name" field.
func (u *AppAccountUpsert) SetName(v string) *AppAccountUpsert {
	u.Set(appaccount.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AppAccountUpsert) UpdateName() *AppAccountUpsert {
	u.SetExcluded(appaccount.FieldName)
	return u
}

// SetPicture sets the "picture" field.
func (u *AppAccountUpsert) SetPicture(v string) *AppAccountUpsert {
	u.Set(appaccount.FieldPicture, v)
	return u
}

// UpdatePicture sets the "picture" field to the value that was provided on create.
func (u *AppAccountUpsert) UpdatePicture() *AppAccountUpsert {
	u.SetExcluded(appaccount.FieldPicture)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AppAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(appaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AppAccountUpsertOne) UpdateNewValues() *AppAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(appaccount.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(appaccount.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AppAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AppAccountUpsertOne) Ignore() *AppAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppAccountUpsertOne) DoNothing() *AppAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppAccountCreate.OnConflict
// documentation for more info.
func (u *AppAccountUpsertOne) Update(set func(*AppAccountUpsert)) *AppAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppAccountUpsertOne) SetUpdatedAt(v time.Time) *AppAccountUpsertOne {
	return u.Update(func(s *AppAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppAccountUpsertOne) UpdateUpdatedAt() *AppAccountUpsertOne {
	return u.Update(func(s *AppAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOidcSubject sets the "oidc_subject" field.
func (u *AppAccountUpsertOne) SetOidcSubject(v string) *AppAccountUpsertOne {
	return u.Update(func(s *AppAccountUpsert) {
		s.SetOidcSubject(v)
	})
}

// UpdateOidcSubject sets the "oidc_subject" field to the value that was provided on create.
func (u *AppAccountUpsertOne) UpdateOidcSubject() *AppAccountUpsertOne {
	return u.Update(func(s *AppAccountUpsert) {
		s.UpdateOidcSubject()
	})
}

// SetEmail sets the "email" field.
func (u *AppAccountUpsertOne) SetEmail(v string) *AppAccountUpsertOne {
	return u.Update(func(s *AppAccountUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AppAccountUpsertOne) UpdateEmail() *AppAccountUpsertOne {
	return u.Update(func(s *AppAccountUpsert) {
		s.UpdateEmail()
	})
}

// SetName sets the "name" field.
func (u *AppAccountUpsertOne) SetName(v string) *AppAccountUpsertOne {
	return u.Update(func(s *AppAccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AppAccountUpsertOne) UpdateName() *AppAccountUpsertOne {
	return u.Update(func(s *AppAccountUpsert) {
		s.UpdateName()
	})
}

// SetPicture sets the "picture" field.
func (u *AppAccountUpsertOne) SetPicture(v string) *AppAccountUpsertOne {
	return u.Update(func(s *AppAccountUpsert) {
		s.SetPicture(v)
	})
}

// UpdatePicture sets the "picture" field to the value that was provided on create.
func (u *AppAccountUpsertOne) UpdatePicture() *AppAccountUpsertOne {
	return u.Update(func(s *AppAccountUpsert) {
		s.UpdatePicture()
	})
}

// Exec executes the query.
func (u *AppAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AppAccountUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AppAccountUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AppAccountCreateBulk is the builder for creating many AppAccount entities in bulk.
type AppAccountCreateBulk struct {
	config
	err      error
	builders []*AppAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the AppAccount entities in the database.
func (_c *AppAccountCreateBulk) Save(ctx context.Context) ([]*AppAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AppAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppAccountCreateBulk) SaveX(ctx context.Context) []*AppAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AppAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AppAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AppAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *AppAccountUpsertBulk {
	_c.conflict = opts
	return &AppAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AppAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AppAccountCreateBulk) OnConflictColumns(columns ...string) *AppAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AppAccountUpsertBulk{
		create: _c,
	}
}

// AppAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of AppAccount nodes.
type AppAccountUpsertBulk struct {
	create *AppAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AppAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(appaccount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AppAccountUpsertBulk) UpdateNewValues() *AppAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(appaccount.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(appaccount.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AppAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AppAccountUpsertBulk) Ignore() *AppAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AppAccountUpsertBulk) DoNothing() *AppAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AppAccountCreateBulk.OnConflict
// documentation for more info.
func (u *AppAccountUpsertBulk) Update(set func(*AppAccountUpsert)) *AppAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AppAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AppAccountUpsertBulk) SetUpdatedAt(v time.Time) *AppAccountUpsertBulk {
	return u.Update(func(s *AppAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AppAccountUpsertBulk) UpdateUpdatedAt() *AppAccountUpsertBulk {
	return u.Update(func(s *AppAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOidcSubject sets the "oidc_subject" field.
func (u *AppAccountUpsertBulk) SetOidcSubject(v string) *AppAccountUpsertBulk {
	return u.Update(func(s *AppAccountUpsert) {
		s.SetOidcSubject(v)
	})
}

// UpdateOidcSubject sets the "oidc_subject" field to the value that was provided on create.
func (u *AppAccountUpsertBulk) UpdateOidcSubject() *AppAccountUpsertBulk {
	return u.Update(func(s *AppAccountUpsert) {
		s.UpdateOidcSubject()
	})
}

// SetEmail sets the "email" field.
func (u *AppAccountUpsertBulk) SetEmail(v string) *AppAccountUpsertBulk {
	return u.Update(func(s *AppAccountUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *AppAccountUpsertBulk) UpdateEmail() *AppAccountUpsertBulk {
	return u.Update(func(s *AppAccountUpsert) {
		s.UpdateEmail()
	})
}

// SetName sets the "name" field.
func (u *AppAccountUpsertBulk) SetName(v string) *AppAccountUpsertBulk {
	return u.Update(func(s *AppAccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AppAccountUpsertBulk) UpdateName() *AppAccountUpsertBulk {
	return u.Update(func(s *AppAccountUpsert) {
		s.UpdateName()
	})
}

// SetPicture sets the "picture" field.
func (u *AppAccountUpsertBulk) SetPicture(v string) *AppAccountUpsertBulk {
	return u.Update(func(s *AppAccountUpsert) {
		s.SetPicture(v)
	})
}

// UpdatePicture sets the "picture" field to the value that was provided on create.
func (u *AppAccountUpsertBulk) UpdatePicture() *AppAccountUpsertBulk {
	return u.Update(func(s *AppAccountUpsert) {
		s.UpdatePicture()
	})
}

// Exec executes the query.
func (u *AppAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AppAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AppAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AppAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
