// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sandbox-nextjs/src/ent/appaccount"
	"github.com/sandbox-nextjs/src/ent/predicate"
)

// AppAccountUpdate is the builder for updating AppAccount entities.
type AppAccountUpdate struct {
	config
	hooks    []Hook
	mutation *AppAccountMutation
}

// Where appends a list predicates to the AppAccountUpdate builder.
func (_u *AppAccountUpdate) Where(ps ...predicate.AppAccount) *AppAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppAccountUpdate) SetUpdatedAt(v time.Time) *AppAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *AppAccountUpdate) SetEmail(v string) *AppAccountUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AppAccountUpdate) SetNillableEmail(v *string) *AppAccountUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AppAccountUpdate) SetName(v string) *AppAccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppAccountUpdate) SetNillableName(v *string) *AppAccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPicture sets the "picture" field.
func (_u *AppAccountUpdate) SetPicture(v string) *AppAccountUpdate {
	_u.mutation.SetPicture(v)
	return _u
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (_u *AppAccountUpdate) SetNillablePicture(v *string) *AppAccountUpdate {
	if v != nil {
		_u.SetPicture(*v)
	}
	return _u
}

// Mutation returns the AppAccountMutation object of the builder.
func (_u *AppAccountUpdate) Mutation() *AppAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppAccountUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppAccountUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := appaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AppAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(appaccount.Table, appaccount.Columns, sqlgraph.NewFieldSpec(appaccount.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(appaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(appaccount.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(appaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Picture(); ok {
		_spec.SetField(appaccount.FieldPicture, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppAccountUpdateOne is the builder for updating a single AppAccount entity.
type AppAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppAccountMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppAccountUpdateOne) SetUpdatedAt(v time.Time) *AppAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEmail sets the "email" field.
func (_u *AppAccountUpdateOne) SetEmail(v string) *AppAccountUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *AppAccountUpdateOne) SetNillableEmail(v *string) *AppAccountUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AppAccountUpdateOne) SetName(v string) *AppAccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppAccountUpdateOne) SetNillableName(v *string) *AppAccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPicture sets the "picture" field.
func (_u *AppAccountUpdateOne) SetPicture(v string) *AppAccountUpdateOne {
	_u.mutation.SetPicture(v)
	return _u
}

// SetNillablePicture sets the "picture" field if the given value is not nil.
func (_u *AppAccountUpdateOne) SetNillablePicture(v *string) *AppAccountUpdateOne {
	if v != nil {
		_u.SetPicture(*v)
	}
	return _u
}

// Mutation returns the AppAccountMutation object of the builder.
func (_u *AppAccountUpdateOne) Mutation() *AppAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the AppAccountUpdate builder.
func (_u *AppAccountUpdateOne) Where(ps ...predicate.AppAccount) *AppAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppAccountUpdateOne) Select(field string, fields ...string) *AppAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AppAccount entity.
func (_u *AppAccountUpdateOne) Save(ctx context.Context) (*AppAccount, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppAccountUpdateOne) SaveX(ctx context.Context) *AppAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppAccountUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := appaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *AppAccountUpdateOne) sqlSave(ctx context.Context) (_node *AppAccount, err error) {
	_spec := sqlgraph.NewUpdateSpec(appaccount.Table, appaccount.Columns, sqlgraph.NewFieldSpec(appaccount.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AppAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, appaccount.FieldID)
		for _, f := range fields {
			if !appaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != appaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(appaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(appaccount.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(appaccount.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Picture(); ok {
		_spec.SetField(appaccount.FieldPicture, field.TypeString, value)
	}
	_node = &AppAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{appaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
