// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/sandbox-nextjs/src/ent/appaccount"
	"github.com/sandbox-nextjs/src/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeAppAccount = "AppAccount"
)

// AppAccountMutation represents an operation that mutates the AppAccount nodes in the graph.
type AppAccountMutation struct {
	config
	op            Op
	typ           string
	id            *int
	created_at    *time.Time
	updated_at    *time.Time
	oidc_subject  *string
	email         *string
	name          *string
	picture       *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*AppAccount, error)
	predicates    []predicate.AppAccount
}

var _ ent.Mutation = (*AppAccountMutation)(nil)

// appaccountOption allows management of the mutation configuration using functional options.
type appaccountOption func(*AppAccountMutation)

// newAppAccountMutation creates new mutation for the AppAccount entity.
func newAppAccountMutation(c config, op Op, opts ...appaccountOption) *AppAccountMutation {
	m := &AppAccountMutation{
		config:        c,
		op:            op,
		typ:           TypeAppAccount,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withAppAccountID sets the ID field of the mutation.
func withAppAccountID(id int) appaccountOption {
	return func(m *AppAccountMutation) {
		var (
			err   error
			once  sync.Once
			value *AppAccount
		)
		m.oldValue = func(ctx context.Context) (*AppAccount, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().AppAccount.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withAppAccount sets the old AppAccount of the mutation.
func withAppAccount(node *AppAccount) appaccountOption {
	return func(m *AppAccountMutation) {
		m.oldValue = func(context.Context) (*AppAccount, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m AppAccountMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m AppAccountMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of AppAccount entities.
func (m *AppAccountMutation) SetID(id int) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *AppAccountMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *AppAccountMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().AppAccount.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *AppAccountMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *AppAccountMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the AppAccount entity.
// If the AppAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppAccountMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *AppAccountMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *AppAccountMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *AppAccountMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the AppAccount entity.
// If the AppAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppAccountMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *AppAccountMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetOidcSubject sets the "oidc_subject" field.
func (m *AppAccountMutation) SetOidcSubject(s string) {
	m.oidc_subject = &s
}

// OidcSubject returns the value of the "oidc_subject" field in the mutation.
func (m *AppAccountMutation) OidcSubject() (r string, exists bool) {
	v := m.oidc_subject
	if v == nil {
		return
	}
	return *v, true
}

// OldOidcSubject returns the old "oidc_subject" field's value of the AppAccount entity.
// If the AppAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppAccountMutation) OldOidcSubject(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldOidcSubject is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldOidcSubject requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldOidcSubject: %w", err)
	}
	return oldValue.OidcSubject, nil
}

// ResetOidcSubject resets all changes to the "oidc_subject" field.
func (m *AppAccountMutation) ResetOidcSubject() {
	m.oidc_subject = nil
}

// SetEmail sets the "email" field.
func (m *AppAccountMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the value of the "email" field in the mutation.
func (m *AppAccountMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old "email" field's value of the AppAccount entity.
// If the AppAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppAccountMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmail is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail resets all changes to the "email" field.
func (m *AppAccountMutation) ResetEmail() {
	m.email = nil
}

// SetName sets the "name" field.
func (m *AppAccountMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *AppAccountMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the AppAccount entity.
// If the AppAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppAccountMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *AppAccountMutation) ResetName() {
	m.name = nil
}

// SetPicture sets the "picture" field.
func (m *AppAccountMutation) SetPicture(s string) {
	m.picture = &s
}

// Picture returns the value of the "picture" field in the mutation.
func (m *AppAccountMutation) Picture() (r string, exists bool) {
	v := m.picture
	if v == nil {
		return
	}
	return *v, true
}

// OldPicture returns the old "picture" field's value of the AppAccount entity.
// If the AppAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *AppAccountMutation) OldPicture(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPicture is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPicture requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPicture: %w", err)
	}
	return oldValue.Picture, nil
}

// ResetPicture resets all changes to the "picture" field.
func (m *AppAccountMutation) ResetPicture() {
	m.picture = nil
}

// Where appends a list predicates to the AppAccountMutation builder.
func (m *AppAccountMutation) Where(ps ...predicate.AppAccount) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the AppAccountMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *AppAccountMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.AppAccount, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *AppAccountMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *AppAccountMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (AppAccount).
func (m *AppAccountMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *AppAccountMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.created_at != nil {
		fields = append(fields, appaccount.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, appaccount.FieldUpdatedAt)
	}
	if m.oidc_subject != nil {
		fields = append(fields, appaccount.FieldOidcSubject)
	}
	if m.email != nil {
		fields = append(fields, appaccount.FieldEmail)
	}
	if m.name != nil {
		fields = append(fields, appaccount.FieldName)
	}
	if m.picture != nil {
		fields = append(fields, appaccount.FieldPicture)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *AppAccountMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case appaccount.FieldCreatedAt:
		return m.CreatedAt()
	case appaccount.FieldUpdatedAt:
		return m.UpdatedAt()
	case appaccount.FieldOidcSubject:
		return m.OidcSubject()
	case appaccount.FieldEmail:
		return m.Email()
	case appaccount.FieldName:
		return m.Name()
	case appaccount.FieldPicture:
		return m.Picture()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *AppAccountMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case appaccount.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case appaccount.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case appaccount.FieldOidcSubject:
		return m.OldOidcSubject(ctx)
	case appaccount.FieldEmail:
		return m.OldEmail(ctx)
	case appaccount.FieldName:
		return m.OldName(ctx)
	case appaccount.FieldPicture:
		return m.OldPicture(ctx)
	}
	return nil, fmt.Errorf("unknown AppAccount field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AppAccountMutation) SetField(name string, value ent.Value) error {
	switch name {
	case appaccount.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case appaccount.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case appaccount.FieldOidcSubject:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetOidcSubject(v)
		return nil
	case appaccount.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	case appaccount.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case appaccount.FieldPicture:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPicture(v)
		return nil
	}
	return fmt.Errorf("unknown AppAccount field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *AppAccountMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *AppAccountMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *AppAccountMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown AppAccount numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *AppAccountMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *AppAccountMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *AppAccountMutation) ClearField(name string) error {
	return fmt.Errorf("unknown AppAccount nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *AppAccountMutation) ResetField(name string) error {
	switch name {
	case appaccount.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case appaccount.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case appaccount.FieldOidcSubject:
		m.ResetOidcSubject()
		return nil
	case appaccount.FieldEmail:
		m.ResetEmail()
		return nil
	case appaccount.FieldName:
		m.ResetName()
		return nil
	case appaccount.FieldPicture:
		m.ResetPicture()
		return nil
	}
	return fmt.Errorf("unknown AppAccount field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *AppAccountMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *AppAccountMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *AppAccountMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *AppAccountMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *AppAccountMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *AppAccountMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *AppAccountMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown AppAccount unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *AppAccountMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown AppAccount edge %s", name)
}
