// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/sandbox-nextjs/src/ent/appaccount"
	"github.com/sandbox-nextjs/src/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appaccountMixin := schema.AppAccount{}.Mixin()
	appaccountMixinFields0 := appaccountMixin[0].Fields()
	_ = appaccountMixinFields0
	appaccountFields := schema.AppAccount{}.Fields()
	_ = appaccountFields
	// appaccountDescCreatedAt is the schema descriptor for created_at field.
	appaccountDescCreatedAt := appaccountMixinFields0[0].Descriptor()
	// appaccount.DefaultCreatedAt holds the default value on creation for the created_at field.
	appaccount.DefaultCreatedAt = appaccountDescCreatedAt.Default.(func() time.Time)
	// appaccountDescUpdatedAt is the schema descriptor for updated_at field.
	appaccountDescUpdatedAt := appaccountMixinFields0[1].Descriptor()
	// appaccount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appaccount.DefaultUpdatedAt = appaccountDescUpdatedAt.Default.(func() time.Time)
	// appaccount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appaccount.UpdateDefaultUpdatedAt = appaccountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appaccountDescEmail is the schema descriptor for email field.
	appaccountDescEmail := appaccountFields[2].Descriptor()
	// appaccount.DefaultEmail holds the default value on creation for the email field.
	appaccount.DefaultEmail = appaccountDescEmail.Default.(string)
	// appaccountDescName is the schema descriptor for name field.
	appaccountDescName := appaccountFields[3].Descriptor()
	// appaccount.DefaultName holds the default value on creation for the name field.
	appaccount.DefaultName = appaccountDescName.Default.(string)
	// appaccountDescPicture is the schema descriptor for picture field.
	appaccountDescPicture := appaccountFields[4].Descriptor()
	// appaccount.DefaultPicture holds the default value on creation for the picture field.
	appaccount.DefaultPicture = appaccountDescPicture.Default.(string)
}
