[tools]
kubectl = "1.36.3"

[env]
_.file = ".env"

[tasks."render"]
run = "kubectl kustomize overlays/${usage_env}/"
usage = '''
arg "<env>" help="Target environment" {
  choices "dev" "staging" "prd"
}
'''

[tasks."apply"]
run = "kubectl apply -k overlays/${usage_env}/"
usage = '''
arg "<env>" help="Target environment" {
  choices "dev" "staging" "prd"
}
'''

[tasks."connect:db"]
run = "kubectl exec -it -n sandbox-app statefulset/sandbox-app-database -- psql -U postgres -d test"
