// Code generated by ent, DO NOT EDIT.

package appaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/sandbox-nextjs/src/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// OidcSubject applies equality check predicate on the "oidc_subject" field. It's identical to OidcSubjectEQ.
func OidcSubject(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldOidcSubject, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldEmail, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldName, v))
}

// Picture applies equality check predicate on the "picture" field. It's identical to PictureEQ.
func Picture(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldPicture, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// OidcSubjectEQ applies the EQ predicate on the "oidc_subject" field.
func OidcSubjectEQ(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldOidcSubject, v))
}

// OidcSubjectNEQ applies the NEQ predicate on the "oidc_subject" field.
func OidcSubjectNEQ(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNEQ(FieldOidcSubject, v))
}

// OidcSubjectIn applies the In predicate on the "oidc_subject" field.
func OidcSubjectIn(vs ...string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldIn(FieldOidcSubject, vs...))
}

// OidcSubjectNotIn applies the NotIn predicate on the "oidc_subject" field.
func OidcSubjectNotIn(vs ...string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNotIn(FieldOidcSubject, vs...))
}

// OidcSubjectGT applies the GT predicate on the "oidc_subject" field.
func OidcSubjectGT(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGT(FieldOidcSubject, v))
}

// OidcSubjectGTE applies the GTE predicate on the "oidc_subject" field.
func OidcSubjectGTE(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGTE(FieldOidcSubject, v))
}

// OidcSubjectLT applies the LT predicate on the "oidc_subject" field.
func OidcSubjectLT(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLT(FieldOidcSubject, v))
}

// OidcSubjectLTE applies the LTE predicate on the "oidc_subject" field.
func OidcSubjectLTE(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLTE(FieldOidcSubject, v))
}

// OidcSubjectContains applies the Contains predicate on the "oidc_subject" field.
func OidcSubjectContains(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldContains(FieldOidcSubject, v))
}

// OidcSubjectHasPrefix applies the HasPrefix predicate on the "oidc_subject" field.
func OidcSubjectHasPrefix(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldHasPrefix(FieldOidcSubject, v))
}

// OidcSubjectHasSuffix applies the HasSuffix predicate on the "oidc_subject" field.
func OidcSubjectHasSuffix(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldHasSuffix(FieldOidcSubject, v))
}

// OidcSubjectEqualFold applies the EqualFold predicate on the "oidc_subject" field.
func OidcSubjectEqualFold(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEqualFold(FieldOidcSubject, v))
}

// OidcSubjectContainsFold applies the ContainsFold predicate on the "oidc_subject" field.
func OidcSubjectContainsFold(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldContainsFold(FieldOidcSubject, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldContainsFold(FieldEmail, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldContainsFold(FieldName, v))
}

// PictureEQ applies the EQ predicate on the "picture" field.
func PictureEQ(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEQ(FieldPicture, v))
}

// PictureNEQ applies the NEQ predicate on the "picture" field.
func PictureNEQ(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNEQ(FieldPicture, v))
}

// PictureIn applies the In predicate on the "picture" field.
func PictureIn(vs ...string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldIn(FieldPicture, vs...))
}

// PictureNotIn applies the NotIn predicate on the "picture" field.
func PictureNotIn(vs ...string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldNotIn(FieldPicture, vs...))
}

// PictureGT applies the GT predicate on the "picture" field.
func PictureGT(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGT(FieldPicture, v))
}

// PictureGTE applies the GTE predicate on the "picture" field.
func PictureGTE(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldGTE(FieldPicture, v))
}

// PictureLT applies the LT predicate on the "picture" field.
func PictureLT(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLT(FieldPicture, v))
}

// PictureLTE applies the LTE predicate on the "picture" field.
func PictureLTE(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldLTE(FieldPicture, v))
}

// PictureContains applies the Contains predicate on the "picture" field.
func PictureContains(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldContains(FieldPicture, v))
}

// PictureHasPrefix applies the HasPrefix predicate on the "picture" field.
func PictureHasPrefix(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldHasPrefix(FieldPicture, v))
}

// PictureHasSuffix applies the HasSuffix predicate on the "picture" field.
func PictureHasSuffix(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldHasSuffix(FieldPicture, v))
}

// PictureEqualFold applies the EqualFold predicate on the "picture" field.
func PictureEqualFold(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldEqualFold(FieldPicture, v))
}

// PictureContainsFold applies the ContainsFold predicate on the "picture" field.
func PictureContainsFold(v string) predicate.AppAccount {
	return predicate.AppAccount(sql.FieldContainsFold(FieldPicture, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AppAccount) predicate.AppAccount {
	return predicate.AppAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AppAccount) predicate.AppAccount {
	return predicate.AppAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AppAccount) predicate.AppAccount {
	return predicate.AppAccount(sql.NotPredicates(p))
}
