apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sandbox-app
resources:
  - api-configmap.yaml
  - ingress.yaml
  - namespace.yaml
  - web-configmap.yaml
  - ../../base
images:
  - name: sandbox-app-api
    newName: registry.example.com/sandbox-app-api
    newTag: latest
  - name: sandbox-app-web
    newName: registry.example.com/sandbox-app-web
    newTag: latest
patches:
  - path: replicas-patch.yaml
