// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppAccount is the predicate function for appaccount builders.
type AppAccount func(*sql.Selector)
