[tools]
go = "1.26.4"
golangci-lint = "2.11.4"

[env]
_.file = ".env.local"

[tasks.dev]
run = "go tool air"

[tasks.build]
run = "go build -o ./tmp/ ./src"

[tasks.run]
run = "go run src/main.go"

[tasks.install]
run = "go mod tidy"

[tasks."migrate:up"]
run = "go tool goose -dir ./migrations postgres \"$DATABASE_URL\" up"

[tasks."migrate:down"]
run = "go tool goose -dir ./migrations postgres \"$DATABASE_URL\" down"

[tasks.format]
run = "go fmt ./..."

[tasks."format:check"]
run = "test -z \"$(gofmt -l .)\""

[tasks.lint]
run = "golangci-lint run ./..."

[tasks."lint:config-chk"]
run = "golangci-lint config verify"

[tasks.test]
run = "go test ./..."

[tasks.ci]
run = [
  { task = "build" },
  { tasks = [
    "format",
    "lint",
    "test",
  ] },
]
